version: 2.1

            
jobs:

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm i
            npm run build  
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout 
      - run:
          name: test backend
          command: |
            cd backend
            npm i
            npm test
            
workflows:
  default:
    jobs:
      - build-backend
      - test-backend:
          requires: [build-backend]
